### ISSUE TITLE
Unstable test in master build

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#168]
**Describe the bug**
Build test should consistently pass or fail 

**To Reproduce**
Create PR ( no backend changes)
`org.molgenis.emx2.graphql.TestGraphqlDatabaseFields > testCreateAndDeleteSchema FAILED
    java.lang.AssertionError: expected:<8> but was:<9>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.molgenis.emx2.graphql.TestGraphqlDatabaseFields.testCreateAndDeleteSchema(TestGraphqlDatabaseFields.java:41)
14 tests completed, 1 failed`
**Expected behavior**
Backend test should always pass or fail ( no backend code it touched in PR)

**Comment by connoratrug** [comment]
possibly a due to timing issue ( create not finished before count is done in assert)

**Comment by mswertz** [comment]
This has to do with major parallellism in the unit test, where multiple emx2 instances in parallel interact with the database. As a consequence the tests are sometimes in conflict with eachother. The only solution I see is to disable parallelism which makes the tests slower but more stable. Interesteringly, this happens much less on my own machine and on travis, I suppose because those machines are slower than our mega kubernetes cluster.
