### ISSUE TITLE
Variable explorer shows 'mapped by none' when there isn't a mapping to the first variable (but there is to a repeat)

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#1894]
**What version of EMX2 are you using (see footer)**
vxx.yy.zz

**Describe the bug**

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/
2. Go to [variable explorer](https://data-catalogue.molgeniscloud.org/catalogue/catalogue/#/variable-explorer)
3. Select a variable that has only mappings to a repeat, for example 'height' 
<img width="1452" alt="Screenshot 2022-12-12 at 16 05 43" src="https://user-images.githubusercontent.com/8653334/207079765-5e057df2-c65c-4c69-93cc-b612d0dbd0cd.png">
4. Mapped by shows none, but in the details overview you see mappings to repeats
<img width="1376" alt="Screenshot 2022-12-12 at 16 07 17" src="https://user-images.githubusercontent.com/8653334/207080045-a8d15ad1-45e5-46f3-807d-bd5807545211.png">

**Expected behavior**
Mapped by shows all cohorts, regardless if only mapped to a repeats

**Comment by connoratrug** [comment]
look like only the first variable ( base variable) is used to construct the mapped by. This should use all repeats to construct the mapped by list.

see (https://github.com/molgenis/molgenis-emx2/blob/bae4195e9e2252b4579bd9af2c8352408eee5426/apps/catalogue/src/store/actions.js#L220)

**Comment by EleanorHyde-UMCG** [comment]
In addition, if there is no cohort with a mapping to the first variable (only to repeats), the link to the harmonisation tab doesn't work either (because no information about mappings can be retrieved):

in Acc:
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/76206da9-8204-44ba-a4f3-a3b522206425)
Clicking on the harmonisation tab has no effect.
