### ISSUE TITLE
A table entry with an ontology reference cannot be saved

### ISSUE THREAD

**Issue by YpeZ** [molgenis/molgenis-emx2#2259]
**What version of EMX2 are you using (see footer)**
v8.174.4

**Describe the bug**
When creating an entry in a table with a field that references an ontology, the value can be selected from the dropdown menu, but not be saved, resulting in an error.

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'
2. Create a new database with a single table.
3. Add a column to this table with columnType ontology, referencing another database in refSchema dropdown menu (when #2258 is fixed), or upload attached molgenis.csv schema
4. Try adding a row by filling in the dialog.
5. See error

**Expected behavior**
The row should save without error.

**Screenshots**
Selecting an entry in the dropdown list works fine
![image](https://user-images.githubusercontent.com/14897333/233969815-f4064b7e-1e9a-4716-98a8-d8041a14a80e.png)

When trying to save, an error message is shown and the entry is not saved
![image](https://user-images.githubusercontent.com/14897333/233970133-e11e298c-7159-4fd0-86a5-ff265fa6567d.png)

**Additional context**
The attached schema

[molgenis.csv](https://github.com/molgenis/molgenis-emx2/files/11309377/molgenis.csv)

**Comment by chinook25** [comment]
@YpeZ The problem here is that Cohort is not an ontology and it should be set as a ref. If changed to ref it works for me, also changing it to an actual ontology e.g. age groups also works. Is this also the case for you or am I missing a case? 
Also I since 2258 is fixed it should not be possible anymore to enter the faulty case inside the schema editor, so only by uploading faulty schema's it's possible to recreate the situation now.
