### ISSUE TITLE
Director App: Consistency in contact information on biobank/collection and network cards

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-emx2#3088]
**Directory App**
The contact information etc on biobank/collection and network cards should be the same/consistent

=> Reuse views (e.g. collections under biobanks & collections under networks)

Contact information:
Order:
PI
Contact + email
address
website

**Comment by konstantina-gkp** [comment]
Apart from a contact person, each biobank has a "Head of Biobank/PI" assigned. However, this is not the case for the networks, since they only have a contact person and not a "Head of Network". How can we make this more consistent?

**Comment by chinook25** [comment]
What if information is not available? Should the header be shown (like Head/Pi here: https://bbmri-emx2-test.molgeniscloud.org/ERIC/directory/#/biobank/bbmri-eric:ID:EXT_ACU) or should it be hidden.

**Comment by chinook25** [comment]
Which contact information should be shown? Currently it differ per view and there is even more available in the database.

**Comment by chinook25** [comment]
Head/PI is a specific column in the Biobanks table and not part of the contact information. I think it would be better to leave it apart like it is now, and not make it a special case (i.e. leave it as it is).

**Comment by chinook25** [comment]
With address you mean of the contact person (I guess, since I don't see any other)? 
Where is the website available? I cannot find it in the tables.

**Comment by esthervanenckevort** [comment]
> What if information is not available? Should the header be shown (like Head/Pi here: https://bbmri-emx2-test.molgeniscloud.org/ERIC/directory/#/biobank/bbmri-eric:ID:EXT_ACU) or should it be hidden or have a warning (e.g. `no head available`).

If it is not available we don't show anything. Showing a warning is not useful since the person who uses the Directory can't edit it in most cases. Contact information is required I believe (but double check the data model).

> Head/PI is a specific column in the Biobanks table and not part of the contact information. I think it would be better to leave it apart like it is now, and not make it a special case (i.e. leave it as it is).

The idea is that any place where we have a field that refers to a record in the persons table that we display the same information. 

> With address you mean of the contact person (I guess, since I don't see any other)? Where is the website available? I cannot find it in the tables.

Address is the address of the contact person, this is shown in addition to the default information

Website is the url field in biobank/collection/network

> Which contact information should be shown? Currently it differ per view and there is even more available in the database.
For each person record the following information should be shown if available:
- title before name, first name, last name, title after name and email
