### ISSUE TITLE
Filter on cohorts in the SSR catalogue variable view

### ISSUE THREAD

**Issue by marijevdgeest** [molgenis/molgenis-emx2#3193]
**Is your feature request related to a problem? Please describe.**
As researcher or datamanager I want to be able to filter on cohorts of interest, so I only see variables that have information for one of the filtered cohorts available.

**Describe the solution you'd like**
Filter for cohorts (within the selected network). When one or more cohorts are selected, only variables that have info for one of the selected cohorts are shown and the harmonization matrix is filtered for these selected cohorts as well.

**Comment by EleanorHyde-UMCG** [comment]
As requested in the meeting yesterday morning, here (rather than in a separate bug) the request to make small changes to the text, please:

1. On https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/all/variables please change "A complete overview of available variables." to "A complete overview of harmonised variables." (NB British spelling) This probably gets automatically changed on the network overview of variables as well (eg https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/LongITools/variables) - please check that it does and otherwise please change it there, too.

2. Please correct the spelling on the network's page (eg https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/LongITools), and put 'Harmonised variables' under the variables button.

Thanks!
