### ISSUE TITLE
Filter results are incorrect when combining diagnosis available and category

### ISSUE THREAD

**Issue by esthervanenckevort** [molgenis/molgenis-emx2#3341]
**What version of EMX2 are you using (see footer)**
v10.34.2

**Describe the bug**
When I search for diagnosis available 'C18 Malignant Neoplasm of Colon' and category 'COVID-19' I expect to only see those collections that match both.

**To Reproduce**
1. Go to 'https://directory-emx2-acc.molgenis.net/'
2. Click on 'Diagnosis available' and search for C18 and select this code.
3. Click on 'Categories' and select COVID-19

**Expected behavior**
Expected to see only collections that match both. Currently for the production server this is only 'Main Collection of the BioMaterial Bank Nord' 

**Actual results**
I see multiple results that match on 'COVID-19' but not on 'C18 Malignant Neoplasm of the Colon'.

Actual results:
<img width="1616" alt="Screenshot 2024-02-02 at 10 55 13" src="https://github.com/molgenis/molgenis-emx2/assets/1942445/dabfd719-901c-46f3-b4a6-dfd13b7d711a">

Expected results (screenshot from production)
<img width="1616" alt="Screenshot 2024-02-02 at 10 55 18" src="https://github.com/molgenis/molgenis-emx2/assets/1942445/13d7bd0b-44dc-479c-82fa-0b68a52dd002">

**Comment by konstantina-gkp** [comment]
I checked the issue. It appears that when searching for diagnosis available 'C18 Malignant Neoplasm of Colon' and category 'COVID-19', the query actually returns all the biobanks that match both filters. E.g., Amsterdam UMC Biobank: Location AMC has collections for both  'C18 Malignant Neoplasm of Colon' and 'COVID-19'. I think the directory app is not displaying a blue label for the diagnosis filter at the section "Because you searched for: ". When combining the diagnosis filter with other filters (e.g., material type buffy coat), the app only shows a blue label for the "buffy coat". Or am I missing something?
![AMC](https://github.com/molgenis/molgenis-emx2/assets/143411718/bfcd8ef6-2e45-4b54-96c7-e9599b780709)
![AMC_covid](https://github.com/molgenis/molgenis-emx2/assets/143411718/c293ea4e-ba58-40b4-92d8-1f664c56642d)

**Comment by esthervanenckevort** [comment]
Compare it with production.
The search is expected to behave as an AND between the different facets. Currently it is behaving as an OR between the different facets.
https://directory-emx2-acc.molgenis.net/ERIC/directory/#/catalogue?Diagnosisavailable=QzE4LjAsQzE4LjEsQzE4LjIsQzE4LjMsQzE4LjQsQzE4LjUsQzE4LjYsQzE4LjcsQzE4LjgsQzE4LjksQzE4&Categories=covid19

vs

https://directory.bbmri-eric.eu/#/catalogue?diagnosis_available=urn%3Amiriam%3Aicd%3AC18&categories=covid19
