### ISSUE TITLE
'Variables' page is very slow to load

### ISSUE THREAD

**Issue by timcadman** [molgenis/molgenis-emx2#3481]
**What version of EMX2 are you using (see footer)**
v10.37.1

**Describe the bug**
On the beta catalogue, when clicking the 'variable' button in the top right corner of screen it takes approximately 12 seconds for the variable page to load.

**To Reproduce**
Follow test-plan 1 until step 8:
https://github.com/molgenis/molgenis-emx2/pull/3135/files#diff-87d0d7863e01e079d5bbe8c69f27fc8a36ede2c1faea26e077f7dee7cbc4e32c 

**Expected behavior**
The variable pages loads within a couple of seconds.

**Desktop (please complete the following information):**
 - OS: masOS Sonoma 14.3.1
 - Browser: Chrome 
 - Version 122.0.6261.69

**Additional context**
Connecting via a wireless network at ISGlobal university in Barcelona

**Comment by timcadman** [comment]
This appears to be unique to the ECCN network - when trying with either EOSC or EHEN the variables page loads within a couple of seconds

**Comment by connoratrug** [comment]
The basic page query ( called 'VariablesPage') is big ( due to the fact it fetches the data not only for the variable lsit , but also the data needed to render the harmonization table), but not extremely big . 

Running this query without Cohort- and Variable filter values it takes around:

 190 to 240 ms round trip from fetch to response. 

This is not super fast but oke for a complex page like did. 
However when we add 'typical' filter values ( needed for the sub catalogue structure ( non the user set page filters )  , for example 
 ```
{
    "orderby": {
        "label": "ASC"
    },
    "variablesFilter": {
        "resource": {
            "id": {
                "equals": [
                    "LongITools_CDM",
                    "LifeCycle_CDM"
                ]
            }
        }
    },
    "cohortsFilter": {
        "networks": {
            "equals": [
                {
                    "id": "LongITools"
                }
            ]
        }
    }
}
```

the response time jumps up to 4 seconds ( it takes 20 times al long ), 4 seconds makes the page feel 'slow' or 'broken' ( this is just a example other queries / data sets give other resp times
