### ISSUE TITLE
Split up cohort view general design into two sections: General design and Population and add some missing data items

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3609]
**What version of EMX2 are you using (see footer)**
v10.49.10

**Describe the bug**
Some data items for cohorts are not shown. 

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/cohorts/testCohort1
2. Scroll down to section General design.
3. The section can be subdivided into 2 sections as such:

“General design”, with fields: 
Cohort type
Design
Design description
Design schematic
Collection type
Start/end year
Design paper
PID

"Population", with fields: 
Countries (renamed from Population, does not cover the content)
Regions
Number of participants
Number of participants with samples
Population age groups
Main medical condition
_ICDO site (Data resources.population oncology topology; ontology_array)
ICDO morphology (Data resources.population oncology morphology; ontology_array)
Inclusion criteria (Cohorts.inclusion criteria; ontology_array)
Other inclusion criteria (Cohorts.other inclusion criteria; text)_

New fields in italics

![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/b594e174-82de-4169-b356-0958d3d3f62e)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by connoratrug** [comment]
This looks more like a feature request then an issue or bug, please consider using the feature request template or create a trac ticket. The feature requests template has several relevant questions; https://github.com/molgenis/molgenis-emx2/issues/new?assignees=&labels=&projects=&template=feature_request.md&title=

**Comment by BrendaHijmans** [comment]
I think moving this to a feature request just creates more work. Can't this just be seen as a feature request? The request text will not be changed by moving from a bug request to a feature request. In my opinion it can also be treated as a bug, because the items are not shown, but should be shown.

**Comment by mswertz** [comment]
I think Connor simply asks to check the standard feature request questions:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
