### ISSUE TITLE
Cannot view Cohorts table due to time out error

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#3652]
**What version of EMX2 are you using (see footer)**
10.58.0, 10.58.1, also older 10.48.8

**Describe the bug**
I cannot view the Cohorts table due to an error.
![image](https://github.com/molgenis/molgenis-emx2/assets/42644481/c242bbee-9e61-4288-a773-807b8bcd8db6)

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/catalogue/tables/#/Cohorts

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marijevdgeest** [comment]
Same happens for the networks table!

**Comment by DickPostma** [comment]
After long searching and importing and exporting this command did the trick. 

`sudo -u postgres vacuumdb -Z --all`

Probably there is a big overhead with the catalogue data in the SQL tables. Maybe good to sort things out if it data/content related or sql (column width etc..) ?

**Comment by EleanorHyde-UMCG** [comment]
As requested in the meeting this morning, here (rather than in a separate bug) the request to make small changes to the text, please:

1. On https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/all/variables please change "A complete overview of available variables." to "A complete overview of harmonised variables."  (NB British spelling) This probably gets automatically changed on the network overview of variables as well (eg https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/LongITools/variables) - please check that it does and otherwise please change it there, too.
2. Please correct the spelling on the network's page (eg https://data-catalogue.molgeniscloud.org/catalogue/ssr-catalogue/LongITools), and put 'Harmonised variables' under the variables button.

Thanks!
