### ISSUE TITLE
fix: add missing items to cohort details view

### ISSUE THREAD

**Issue by mswertz** [molgenis/molgenis-emx2#3773]
Todo: 
- [ ] change the label of the field under Population from 'Main medical condition' to 'Population disease' ( see note)

**Comment by EleanorHyde-UMCG** [comment]
[Spec in SharePoint ](https://umcgonline.sharepoint.com/:x:/r/sites/SGCohortcatalogues/Gedeelde%20documenten/Test%20activities%20Feb%2024/Specs%20for%20feature%20requests/20240524%20cohort%20page%20fields.xlsx?d=wb4867de434d44e39831f036aa8146c2b&csf=1&web=1&e=7goKDF)  copied in screenshots here below (notes:
1) Contact button and what happens behind it can stay the same for now. We will change this after discussions with UMCG.
2) The two fields greyed out below are not required.)



![Image](https://github.com/molgenis/molgenis-emx2/assets/80456579/5996b4af-fe7d-456d-922f-a5a228e35627)



![Image](https://github.com/molgenis/molgenis-emx2/assets/80456579/2ba2d8fd-0fa3-42c8-a96d-acf78063849c)



![Image](https://github.com/molgenis/molgenis-emx2/assets/80456579/b9d05880-1814-455e-bf61-1bb3e28e4dcb)

**Comment by connoratrug** [comment]
@EleanorHyde-UMCG please put the items in this issue , thanks !

**Comment by EleanorHyde-UMCG** [comment]
What else do you need, @connoratrug? (link to Excel and screen shots are above)

**Comment by EleanorHyde-UMCG** [comment]
note 3) please also change the 'contact & contributors' chapter name on the left hand side to match the new block name on the right hand side.

**Comment by EleanorHyde-UMCG** [comment]
to do list added at the top

**Comment by EleanorHyde-UMCG** [comment]
The two added fields look good.  I will check out what the issue was with Population disease.  In the meantime, is there a reason why these indents with Data use conditions and Release type occur?

![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/df80e0e4-0aa3-4daa-a4ae-57d8ccc54639)

**Comment by EleanorHyde-UMCG** [comment]
I agree that Main medical condition and Population disease are two separate fields. I suggest we leave the label as it is now, as long as it's showing the correct information.  Because:

These are the contents of the subcohorts table in acc, showing the Main medical condition for the subcohorts for testcohort1 and testcohort2:

![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/606edcda-f1f2-49d4-aab1-2c7016d41825)

So for testcohort1 I would expect to see the following under Main medical condition:
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/9c1a4c6c-41e5-4d76-894d-b5c3e3ff8694)

But instead I see this:
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/5f0510ab-ff84-4c53-b06d-bca97338effc)


And for testcohort2 I would expect this:
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/2d7d27b5-d5ba-4f03-8ec8-ddc5635e77a8)


But instead I see this:
![image](https://github.com/molgenis/molgenis-emx2/assets/80456579/ca1982e9-f5fb-4b16-904c-360b5cd0e54c)

**Comment by EleanorHyde-UMCG** [comment]
@connoratrug which info are you missing here? Can you let me know how the Main medical condition field is being filled?

@BrendaHijmans  do you have an opinion about the Publications field? (See Connor's comment above) Leave out for now?

**Comment by EleanorHyde-UMCG** [comment]
@connoratrug let's discuss this tomorrow - I wonder whether we're filling the Main medical condition field correctly.

**Comment by EleanorHyde-UMCG** [comment]
Discussion with @connoratrug. The way it is now was set up for UMCG and they are happy with it. Wait until the new data model and potential new fields are there to see whether we need to correct this.
