### ISSUE TITLE
UMCG Data Catalogue wants to have spaces the name of items in forms

### ISSUE THREAD

**Issue by BrendaHijmans** [molgenis/molgenis-emx2#419]
**Is your feature request related to a problem? Please describe.**
UMCG Data Catalogue people want to be able to change the names of the items in forms, e.g. ageMin should be Minimum age.

**Describe the solution you'd like**
Add a label to the data model.
=> we will not add labels, however, we will enable users to add spaces to their names so they can say 'Minimum Age'.

**Describe alternatives you've considered**

**Additional context**

**Comment by mswertz** [comment]
I dont like this idea. Please first focus on useful descriptions

**Comment by mswertz** [comment]
I have been thinking about this for past 2 years and I really don't want 'name' and 'label' as separate config. This leads typically to bad data science (MOLGENIS is a scientific database) where label and name become so different that nobody gets it.

However we could do some beautifications in the user interface, and I have two ideas:
1. In the forms we automatically convert camelCase to sentence. E.g. name=minumumAge becomes 'Mininum Age'. 
2. Or reverse, we allow designer to use spaces and convert this to camelCase behind scene. E.g. name='Minimum Age' becomes 'minimumAge'

Option 2 has advantages because we could also have more difficult cases, such as special characters, extra spaces etc.

Both options ensure a deterministic relationship between 'name' and 'label' ensuring the system stays comprehensible for both data scientists and more naive users.

**Comment by BrendaHijmans** [comment]
Both options sound good to me! How would you handle column names in data input files in option 2?

**Comment by mswertz** [comment]
Good question. What do you prefer?

**Comment by BrendaHijmans** [comment]
If you choose option 2, I think you should allow for the 'designer' text to be used as column name, but camelCase is more convenient. So I would say make it possible to use both.

Option 1 seems handier to me. It is more straight forward and will be less confusing to users.

**Comment by mswertz** [comment]
> So I would say make it possible to use both.

Okay, so that would mean that during import we apply both 'camelCase' and 'sentence case' representations to match the column headers of imported file agains the database schema. That probably is possible :-)

**Comment by mswertz** [comment]
related to molgenis backlog https://trac.molgeniscloud.org/ticket/8453
