### ISSUE TITLE
Molgenis home button seems to be broken

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-emx2#556]
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
The molgenis logo (screenshot yellow circle) does not work as a home button, is not clickable

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/'
2. Click on 'Molgenis' top left menu bar

**Expected behavior**
I expect to be redirected to the home page or in case of selected database to go to its respective home page

**Screenshots**
![molgenis-logo-home-button](https://user-images.githubusercontent.com/4077085/133611547-4aba7017-1f8d-4893-a79d-91556f6de33c.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser Chromium
 - Version 93.0.4577.82

- Browser Firefox
- version 92

**Comment by mswertz** [comment]
I have removed this option because it was confusing where the 'home' button should leave. I will close this issue until you can give me convincing story on where the home button should point to, i.e, the root of the molgenis app? or the root of the schema? and if you are not signed in you might end up in 'help'/
