### ISSUE TITLE
Download then upload of complete schema fails 

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#824]
**What version of EMX2 are you using (see footer)**
8.33.0

**Describe the bug**
Import failed: Transaction failed: insert or update on table "CollectionEvents" violates foreign key (ref_array) constraint.Key ("sampleCategories")=(Other) is not present in table "SampleCategories", column(s)("name"): Cannot commit transaction in 9298ms

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'](https://catalogue-acc.molgeniscloud.org/UMCG/updownload/
2. Download as zip
3. Upload into empty database

**Expected behavior**
Upload success, data and schema are copied into new schema

**Comment by mswertz** [comment]
duplicate issue with #594; will require data model to not inherit from OntologyTerm

**Comment by connoratrug** [comment]
or the way the model data is persisted could be changed, suggest to make this a high priority issue due to the impact on the data ( model )

**Comment by mswertz** [comment]
Yes we (data managers) know. 

Meanwhile the workaround has been applied at most systems but it seems not in your data: ensure that your OntologyTerms are globally unique (i.e. accross all tableExtends=OntologyTerms'.

 Now you have issue that 'Other' is used in multiple OntologyTerms. Because they all inherit from same superclass that doesn't fail. If you here choose 'Other sample categories' you would be able to workaround this issue.

N.B. We intend to make OntologyTerm a special data type so end-users don't need to create the ontology table structures by hand for each lookup.
